spring:
    datasource:
        password: pass
        url: jdbc:postgresql://localhost:5432/scooter_vehicle
        username: scooter
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    kafka:
        producer:
            properties:
                client.id: "test"
                acks: "1"
                retries: "5"
                key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
                value.serializer: "org.apache.kafka.common.serialization.JsonSerializer"
                linger.ms: "10"
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
